// Code generated by goctl. DO NOT EDIT.
package types

type FileChunkUploadFinishRequest struct {
	Md5        string        `json:"md5"`
	Name       string        `json:"name"`
	Ext        string        `json:"ext"`
	Size       int64         `json:"size"`
	Key        string        `json:"key"`
	UploadId   string        `json:"uploadId"`
	CosObjects []*CosObjecet `json:"cosObjects"`
}

type CosObjecet struct {
	PartNumber int    `json:"partNumber"`
	Etag       string `json:"etag"`
}

type FileChunkUploadFinishResponse struct {
	Msg string `json:"msg"`
}

type FileChunkUploadRequest struct {
}

type FileChunkUploadResponse struct {
	Etag string `json:"etag"`
}

type FileUploadPrepareRequest struct {
	Md5  string `json:"md5"`
	Name string `json:"name"`
	Ext  string `json:"ext"`
}

type FileUploadPrepareResponse struct {
	Identity string `json:"identity"`
	UploadId string `json:"uploadId"`
	Key      string `json:"key"`
	Msg      string `json:"msg"`
}

type RefreshAuthRequest struct {
}

type RefreshAuthResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	Msg          string `json:"msg"`
}

type SaveSharedFileRequest struct {
	RepositoryIdentity string `json:"repositoryIdentity"`
	ParentId           int64  `json:"parentId"`
}

type SaveSharedFileResponse struct {
	Identity string `json:"identity"`
	Msg      string `json:"msg"`
}

type ShareBasicDetailsRequest struct {
	Identity string `json:"identity"`
}

type ShareBasicDetailsResponse struct {
	RepositoryIdentity string `json:"repositoryIdentity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
	Msg                string `json:"msg,optional"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryIdentity string `json:"userRepositoryIdentity"`
	ExpireTime             int    `json:"expireTime"`
}

type ShareBasicCreateResponse struct {
	Identity string `json:"identity"`
	Msg      string `json:"msg"`
}

type UserFileMoveRequest struct {
	Identity       string `json:"identity"`
	ParentIdentity string `json:"parentIdentity"`
}

type UserFileMoveResponse struct {
	Msg string `json:"msg"`
}

type UserFileDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResponse struct {
	Msg string `json:"msg"`
}

type UserFolderCreateRequest struct {
	ParentId int    `json:"parentId"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
	Msg      string `json:"msg"`
}

type UserFileNameUpdateRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameUpdateResponse struct {
	Msg string `json:"msg"`
}

type UserFileListRequest struct {
	Id   int64 `json:"id, optional"`
	Page int   `json:"page, optional"`
	Size int   `json:"size, optional"`
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
	Msg   string      `json:"msg"`
}

type UserFile struct {
	Id           int64  `json:"id"`
	Identity     string `json:"identity"`
	RepoIdentity string `json:"repoIdentity"`
	Name         string `json:"name"`
	Ext          string `json:"ext"`
	Path         string `json:"path"`
	Size         int64  `json:"size"`
}

type UserRepoSaveRequest struct {
	ParentId       int    `json:"parentId"`
	RepoInentityId string `json:"repoInentityId"`
	Ext            string `json:"ext"`
	Name           string `json:"name"`
}

type UserRepoSaveResponse struct {
	Msg      string `json:"msg"`
	Inentity string `json:"inentity"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type UserDetailsRequest struct {
	Indentity string `json:"indentity"`
}

type UserDetailsResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type EmailCodeRequest struct {
	Email string `json:"email"`
}

type EmailCodeResponse struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type UserRegisterResponse struct {
	Msg string `json:"msg"`
}

type FileUploadRequest struct {
	Hash string `json:"hash, optional"`
	Name string `json:"name, optional"`
	Ext  string `json:"ext, optional"`
	Size int64  `json:"size, optional"`
	Path string `json:"path, optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Msg      string `json:"msg"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}
